version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  web:
    build: ./
    command: ./bin/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
     .env
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
