pipeline {
  agent any

  stages {
    stage('Install dependencies') {
      steps {
        sh 'bundle install'
      }
    }
    stage('Run Tests') {
      steps {
        sh 'bundle exec rspec'
      }
    }
    stage('Build Docker image') {
      steps {
        sh 'docker build -t user-task-api .'
      }
    }
  }
}
